# BifacialvF- PVMISMATCH Testing Landscape and Portrait Results.

In [2]:
import bifacialvf
import pandas as pd

In [11]:
frontGTIrow=[53.01720526, 55.32772694, 55.78247445, 55.69094834, 55.62417481, 55.59217422]
backGTIrow=[8.550246348, 4.626045218, 4.406054333, 6.141527447, 9.211464402, 12.87567548]


portraitorlandscape='portrait'
sensorsy=len(frontGTIrow)
debug=True
                       
cellCenterPVM, stdpl, cellsx, cellsy = bifacialvf.analysis.setupforPVMismatch(portraitorlandscape=portraitorlandscape, sensorsy=sensorsy, numcells=72)

PowerAveraged, PowerDetailed, sunmatAveraged, sunmatDetailed = bifacialvf.analysis.calculateVFPVMismatch(cellCenterPVM=cellCenterPVM, stdpl=stdpl, cellsx=cellsx, cellsy=cellsy, sensorsy=sensorsy, frontGTIrow=frontGTIrow, backGTIrow=backGTIrow, bififactor=1.0, debug=debug)

print("Results: ", round(PowerAveraged,3), round(PowerDetailed,2))

print(portraitorlandscape, "Cellsx", cellsx, "Cellsy", cellsy)
print(pd.DataFrame(stdpl))
print(pd.DataFrame(sunmatAveraged).round(3))
pd.DataFrame(sunmatDetailed).round(3)

Results:  11.631 11.41
portrait Cellsx 6 Cellsy 12
     0   1   2   3   4   5
0    0  23  24  47  48  71
1    1  22  25  46  49  70
2    2  21  26  45  50  69
3    3  20  27  44  51  68
4    4  19  28  43  52  67
5    5  18  29  42  53  66
6    6  17  30  41  54  65
7    7  16  31  40  55  64
8    8  15  32  39  56  63
9    9  14  33  38  57  62
10  10  13  34  37  58  61
11  11  12  35  36  59  60
        0      1      2      3      4      5
0   0.063  0.063  0.063  0.063  0.063  0.063
1   0.063  0.063  0.063  0.063  0.063  0.063
2   0.063  0.063  0.063  0.063  0.063  0.063
3   0.063  0.063  0.063  0.063  0.063  0.063
4   0.063  0.063  0.063  0.063  0.063  0.063
5   0.063  0.063  0.063  0.063  0.063  0.063
6   0.063  0.063  0.063  0.063  0.063  0.063
7   0.063  0.063  0.063  0.063  0.063  0.063
8   0.063  0.063  0.063  0.063  0.063  0.063
9   0.063  0.063  0.063  0.063  0.063  0.063
10  0.063  0.063  0.063  0.063  0.063  0.063
11  0.063  0.063  0.063  0.063  0.063  0.063

        0      1      2      3      4      5
0   0.061  0.061  0.061  0.061  0.061  0.061
1   0.060  0.060  0.060  0.060  0.060  0.060
2   0.060  0.060  0.060  0.060  0.060  0.060
3   0.060  0.060  0.060  0.060  0.060  0.060
4   0.061  0.061  0.061  0.061  0.061  0.061
5   0.061  0.061  0.061  0.061  0.061  0.061
6   0.063  0.063  0.063  0.063  0.063  0.063
7   0.064  0.064  0.064  0.064  0.064  0.064
8   0.066  0.066  0.066  0.066  0.066  0.066
9   0.068  0.068  0.068  0.068  0.068  0.068
10  0.068  0.068  0.068  0.068  0.068  0.068
11  0.068  0.068  0.068  0.068  0.068  0.068

In [12]:
frontGTIrow=[53.01720526, 55.32772694, 55.78247445, 55.69094834, 55.62417481, 55.59217422]
backGTIrow=[8.550246348, 4.626045218, 4.406054333, 6.141527447, 9.211464402, 12.87567548]



portraitorlandscape='landscape'
sensorsy=len(frontGTIrow)
debug = True

cellCenterPVM, stdpl, cellsx, cellsy = bifacialvf.analysis.setupforPVMismatch(portraitorlandscape=portraitorlandscape, sensorsy=sensorsy, numcells=72)

PowerAveraged, PowerDetailed, sunmatAveraged, sunmatDetailed = bifacialvf.analysis.calculateVFPVMismatch(cellCenterPVM=cellCenterPVM, stdpl=stdpl, cellsx=cellsx, cellsy=cellsy, sensorsy=sensorsy, frontGTIrow=frontGTIrow, backGTIrow=backGTIrow, bififactor=1.0, debug=debug)

print("Results: ", round(PowerAveraged,3), round(PowerDetailed,2))

print(portraitorlandscape, "Cellsx", cellsx, "Cellsy", cellsy)
print(pd.DataFrame(stdpl))
print(pd.DataFrame(sunmatAveraged).round(3))
pd.DataFrame(sunmatDetailed).round(3)

Results:  11.503 11.29
landscape Cellsx 12 Cellsy 6
   0   1   2   3   4   5   6   7   8   9   10  11
0   0   1   2   3   4   5   6   7   8   9  10  11
1  23  22  21  20  19  18  17  16  15  14  13  12
2  24  25  26  27  28  29  30  31  32  33  34  35
3  47  46  45  44  43  42  41  40  39  38  37  36
4  48  49  50  51  52  53  54  55  56  57  58  59
5  71  70  69  68  67  66  65  64  63  62  61  60
      0      1      2      3      4      5      6      7      8      9   \
0  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063
1  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063
2  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063
3  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063
4  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063
5  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063  0.063

      10     11
0  0.063  0.063
1  0.063  0.063
2  0.063  0.063
3  0.063  0.063
4  0.063  0.063
5  0.063  0.063

,0,1,2,3,4,5,6,7,8,9,10,11
0,0.062,0.062,0.062,0.062,0.062,0.062,0.062,0.062,0.062,0.062,0.062,0.062
1,0.060,0.060,0.060,0.060,0.060,0.060,0.060,0.060,0.060,0.060,0.060,0.060
2,0.060,0.060,0.060,0.060,0.060,0.060,0.060,0.060,0.060,0.060,0.060,0.060
3,0.062,0.062,0.062,0.062,0.062,0.062,0.062,0.062,0.062,0.062,0.062,0.062
4,0.065,0.065,0.065,0.065,0.065,0.065,0.065,0.065,0.065,0.065,0.065,0.065
5,0.068,0.068,0.068,0.068,0.068,0.068,0.068,0.068,0.068,0.068,0.068,0.068

In [ ]:
import pvmismatch

frontGTIrow=[53.01720526, 55.32772694, 55.78247445, 55.69094834, 55.62417481, 55.59217422]
backGTIrow=[8.550246348, 4.626045218, 4.406054333, 6.141527447, 9.211464402, 12.87567548]




stdpl96=np.array([[0,	23,	24,	47,	48,	71,	72,	95],
    [1,	22,	25,	46,	49,	70,	73,	94],
    [2,	21,	26,	45,	50,	69,	74,	93],
    [3,	20,	27,	44,	51,	68,	75,	92],
    [4,	19,	28,	43,	52,	67,	76,	91],
    [5,	18,	29,	42,	53,	66,	77,	90],
    [6,	17,	30,	41,	54,	65,	78,	89],
    [7,	16,	31,	40,	55,	64,	79,	88],
    [8,	15,	32,	39,	56,	63,	80,	87],
    [9,	14,	33,	38,	57,	62,	81,	86],
    [10,	13,	34,	37,	58,	61,	82,	85],
    [11,	12,	35,	36,	59,	60,	83,	84]])

stdpl108=np.array([[0,	23,	24,	47,	48,	71,	72,	95, 96],
    [1,	22,	25,	46,	49,	70,	73,	94, 97],
    [2,	21,	26,	45,	50,	69,	74,	93, 98],
    [3,	20,	27,	44,	51,	68,	75,	92, 99],
    [4,	19,	28,	43,	52,	67,	76,	91, 100],
    [5,	18,	29,	42,	53,	66,	77,	90, 101],
    [6,	17,	30,	41,	54,	65,	78,	89, 102],
    [7,	16,	31,	40,	55,	64,	79,	88, 103],
    [8,	15,	32,	39,	56,	63,	80,	87, 104],
    [9,	14,	33,	38,	57,	62,	81,	86, 105],
    [10,	13,	34,	37,	58,	61,	82,	85, 106],
    [11,	12,	35,	36,	59,	60,	83,	84, 107]])

# In [1]: tests
B = pvmismatch.pvmismatch_lib.pvmodule.STD72
A=pvmismatch.pvmismatch_lib.pvmodule.PVmodule(cell_pos=B)
pvsys = pvsystem.PVsystem(numberStrs=1, numberMods=1, pvmods=A)  

# Doing a 72 array on a 72 array
cellsx = 6; cellsy = 12
array_avg_72 = np.ones([cellsy,cellsx])*(0.634)        
cellsx = 8; cellsy = 12
array_avg_96 = np.ones([cellsy,cellsx])*(0.634)   
cellsx = 9; cellsy = 12    
array_avg_108 = np.ones([cellsy,cellsx])*(0.634)        


# Actually do calculations
pvsys.setSuns({0: {0: [array_avg_72, stdpl72]}})
PowerAveraged=pvsys.Pmp

pvsys.setSuns({0: {0: [array_avg_96, stdpl72]}})
PowerAveraged=pvsys.Pmp

pvsys.setSuns({0: {0: [array_avg_96, stdpl96]}})
PowerAveraged=pvsys.Pmp

pvsys.setSuns({0: {0: [array_avg_72, stdpl96]}})
PowerAveraged=pvsys.Pmp

# In [1]: tests
B = pvmismatch.pvmismatch_lib.pvmodule.STD96
A=pvmismatch.pvmismatch_lib.pvmodule.PVmodule(cell_pos=B)
pvsys = pvsystem.PVsystem(numberStrs=1, numberMods=1, pvmods=A)  

# Actually do calculations
pvsys.setSuns({0: {0: [array_avg_72.T, stdpl72.T]}})
PowerAveraged=pvsys.Pmp

pvsys.setSuns({0: {0: [array_avg_96, stdpl72]}})
PowerAveraged=pvsys.Pmp

pvsys.setSuns({0: {0: [array_avg_96.T, stdpl96.T]}})
PowerAveraged=pvsys.Pmp

pvsys.setSuns({0: {0: [array_avg_72, stdpl96]}})
PowerAveraged=pvsys.Pmp


        
    
    if portraitorlandscape == 'portrait':                    
        cellsx = 8
        cellsy = 12
    if portraitorlandscape == 'landscape':
        stdpl = stdpl.transpose()
        cellsx = 12
        cellsy = 8
                                
    if sensorsy != cellsy:
        for i in range (0, cellsy):
            cellCenterPVM.append((i*sensorsy/cellsy+(i+1)*sensorsy/cellsy)/2)